modLoader="javafml"
loaderVersion="${neoforge_loader_range}"
license="${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_homepage}"
logoFile="${mod_icon}"
authors="${mod_author}"
description='''${mod_description}'''
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
versionRange="${neoforge_loader_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="emi"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="CLIENT"
